@startuml init3

class Book{

}

class LibrarySystem{
    + books: Book[]
    + checkoutBook(Book)
    + returnBook(Book)
    + addBook(Book)
    + removeBook(Book)
    + getBooksByAuthor(String author)
    + getBookByArea(String area)
    + getCheckedoutBookByBorrower(User)
    + getBorrowerByBook(Book)
}

LibrarySystem --> Book

class User{

}

together{
    class Staff{

    }

    class Borrower{

    }
}

User -- LibrarySystem
User <|-- Staff
User <|-- Borrower

note bottom of LibrarySystem
Command(){
    if(user is valid)
        command()
}
end note

@enduml