@startuml init2

class Book{
    + author: String
    + subject: String
    + borrower: Borrower
}

class User{

}

together{
    class Staff{

    }

    class Borrower{
        + checkoutBook: : Book[]
    }
}

User <|-- Staff
User <|-- Borrower

class LibrarySystem{
    + books: Book[]
    + checkoutBook(Book)
    + returnBook(Book)
    + addBook(Book)
    + removeBook(Book)
    + getBooksByAuthor(String author)
    + getBookBySubject(String subject)
    + getCheckedoutBookByBorrower(Borrower)
    + getBorrowerByBook(Book)
}

User -- LibrarySystem

note left of LibrarySystem
void checkoutBook(Book b, Borrower borrower){
    b.borrower = borrower
}

void returnBook(Book b){
    b.borrower = null
}

void addBook(Book b){
    this.books.add(b)
}

void removeBook(Book b){
    this.books.remove(b)
}

Book[] getBooksByAuthor(String author){
    Book[] target
    for(Book b : this.books){
        if(b.author.equals(author))
            target.add(b)
    }
    return target
}

Book[] getBooksBySubject(String subject){
    Book[] target
    for(Book b : this.books){
        if(b.subject.equals(subject))
            target.add(b)
    }
    return target
}

Book[] getCheckedoutBookByBorrower(Borrower borrower){
    Book[] target
    for(Book b : this.books){
        if(b.borrower == borrower)
            target.add(b)
    }
    return target
}

Borrower getBorrowerByBook(Book b){
    return b.borrower
}
end note

LibrarySystem --> Book
Borrower -- Book

@enduml