@startuml init1

class Book{

}

class LibrarySystem{
    + books: Book[]
    + checkoutBook(Book)
    + returnBook(Book)
    + addBook(Book)
    + removeBook(Book)
    + getBooksByAuthor(String author)
    + getBookByArea(String area)
    + getCheckedoutBookByBorrower(String borrower)
    + getBorrowerByBook(Book)
}

LibrarySystem --> Book

@enduml