@startuml init3

class Duck{
    + fly()
    + swim()
}

together{
    class MallardDuck{
        + swim()
        + fly()
    }

    class RedheadDuck{
        + swim()
        + fly()
    }

    class RubberDuck{
        + swim()
        + fly()
    }

    class DecoyDuck{
        + swim()
        + fly()
    }
}

note bottom of MallardDuck
    void fly(){
        can fly!
    }
end note

note bottom of RedheadDuck
    void fly(){
        can fly!
    }
end note

note bottom of RubberDuck
    void fly(){
        cannot fly
    }
end note

note bottom of DecoyDuck
    void fly(){
        cannot fly
    }
end note

Duck <|-- MallardDuck
Duck <|-- RedheadDuck
Duck <|-- RubberDuck
Duck <|-- DecoyDuck

@enduml