@startuml step4
left to right direction
class Hospital{
    + physicians: ArrayList<Physician>
}
class Physician

Hospital o---> "1..*\n{registerd}" Physician

class Patient{
    + admitPhysician: Physician
    + treatPhysician: Physician[]
}
Physician "1" --- "0..*" Patient : admit
Physician -[hidden]- Patient
Physician "1..*" --- Patient : treat


@enduml