@startuml overview

skinparam linetype ortho

package aop{
    class TargetClassAware{

    }
}

interface Adviced{
--
管理target, advisor之類的配置的地方
}

class ProxyConfig{
--
放各種setting的地方
}

class AdvicedSupport{
    + advisorChainFactory: AdvisorChainFactory
    + setTarget(target)
    + setAdvisorChainFactory(AdvisorChainFactory)
    + addAdvisor(Advisor)
    + adviceChanged()
    + getInterceptorsAndDynamicInterceptionAdvice(): List<Object>
--
實作Adviced，管理通知advisor
}

interface AdvisorChainFactory{
    + getInterceptorsAndDynamicInterceptionAdvice(): List<Object>
} 

class DefaultAdvisorChainFactory{
    + getInterceptorsAndDynamicInterceptionAdvice(): List<Object>
}

AdvisorChainFactory <|.. DefaultAdvisorChainFactory
AdvicedSupport -> AdvisorChainFactory

class ProxyCreatorSupport{
    - listeners: AdvicedSupportListener[]
    - aopProxyFactory: AopProxyFactory
    + setAopProxyFactory(AopProxyFactory)
    + adviceChanged()
    + activate()
    + createAopProxy(): AopProxy
--
proxy factory的基礎類別
用一個簡單的方式使用AopProxyFactory
**Observer pattern**
}

note right of ProxyCreatorSupport
void adviceChanged(){
    for l in listeners
        l.adviceChanged()
}

void activate(){
    for l in listeners
        l.activate()
}

AopProxy createAopProxy(){
    return this.aopProxyFactory.createAopProxy()
}
end note

ProxyCreatorSupport --> AopProxyFactory

interface AdvicedSupportListener{
    + activate()
    + adviceChanged()
}

ProxyCreatorSupport --> AdvicedSupportListener : notify
AdvicedSupportListener --> ProxyCreatorSupport : attach

class ProxyFactory{
    + getProxy(): Object
--
簡單的得到AopProxy
}

class ProxyFactoryBean{
    + getProxy(): Object
--
在IOC容器中管理Proxy
**Strategy Pattern的不同Context**
}

note bottom of ProxyFactory
Object getProxy(){
    return createAopProxy().getProxy();
}
end note

note bottom of ProxyFactoryBean
Object getProxy(AopProxy aopProxy) {
    return aopProxy.getProxy();
}
end note

TargetClassAware <|-- Adviced
Adviced <|.. AdvicedSupport
ProxyConfig <|-- AdvicedSupport
AdvicedSupport <|-- ProxyCreatorSupport
ProxyCreatorSupport <|-- ProxyFactory
ProxyCreatorSupport <|-- ProxyFactoryBean

interface AopProxyFactory{
    + createAopProx(): AopProxy
    --
    **Strategy pattern**
}

class DefaultAopProxyFactory{
--
根據條件create AopProxy
**simple factory pattern**
}

note bottom of DefaultAopProxyFactory
if(cond A)
    create ObjenesisCglibAopProxy
else if(cond B)
    create JdkDynamicAopProxy
end note

AopProxyFactory <|.. DefaultAopProxyFactory

interface AopProxy{
    + getProxy(): Object
    --
    產生負責處理切面的Proxy
}

class CglibAopProxy{
    --
    Cglib方法創建AopProxy
}

class ObjenesisCglibAopProxy{

}

CglibAopProxy <|-- ObjenesisCglibAopProxy

class JdkDynamicAopProxy{
    JdkDynamic方法創建AopProxy
}

AopProxy <|.. CglibAopProxy
AopProxy <|.. JdkDynamicAopProxy
AopProxyFactory ..> AopProxy : create

package aoplliance{
    interface MethodInvocation{
        + proceed()
    }

    interface MethodInterceptor{
        + invoke(MethodInvocation)
    }

    MethodInterceptor --> MethodInvocation
}

class ReflectiveMethodInvocation{
    + interceptor: MethodInterceptor[]
    + proceed()
    --
    輪流執行這個Invocation(Method)前後的MethodInterceptor
}

ReflectiveMethodInvocation o-- MethodInterceptor
MethodInvocation <|.. ReflectiveMethodInvocation
ObjenesisCglibAopProxy --> ReflectiveMethodInvocation
JdkDynamicAopProxy --> ReflectiveMethodInvocation

@enduml