@startuml proxy2
skinparam linetype ortho



class UserService {
    + method()
}

package Proxy{
    class Proxy {
        + method()
    }
    note top of Proxy
        void method(){
            ReflectiveMethodInvocation().proceed()
        }
        end note

    class ReflectiveMethodInvocation {
        + proceed()
    }
    UserService <|-- Proxy
    Proxy --> ReflectiveMethodInvocation
}


ReflectiveMethodInvocation --> UserService

@enduml